### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by kaosity** [halfuwu/FortniteAutoExporter#10]
Error Below
![image](https://user-images.githubusercontent.com/66960450/107125649-2b329980-6879-11eb-8120-4099b9803118.png)

**Comment by halfuwu** [comment]
Try updating to jdk11: https://drive.google.com/file/d/1yoUcEx1Cq9HndixY4WvFdpg8aWlail16/view?usp=drivesdk
