### ISSUE TITLE
Error when Enabling the addon.

### ISSUE THREAD

**Issue by Spectfx** [halfuwu/FortniteAutoExporter#11]
![image](https://user-images.githubusercontent.com/78743305/107234662-82577c00-69e9-11eb-9292-fcab023502a6.png)
When hitting the checkmark this grey box appears and I'm unable to enable.

**Comment by halfuwu** [comment]
Install this addon first, then try again
https://github.com/Befzz/blender3d_import_psk_psa/tree/master/addons
