### ISSUE TITLE
Error when trying to export. (New Issue)

### ISSUE THREAD

**Issue by ClashSupreme** [halfuwu/FortniteAutoExporter#5]
![jav](https://user-images.githubusercontent.com/73926596/100534085-0bc02600-31d1-11eb-9c51-c0b629d62c89.PNG)

Any fixes?

**Comment by halfuwu** [comment]
Are you sure you're using the 14.30 Pak files? This is pretty much one of the only reasons why you would be getting this error. Your pak directory is set to the default fortnite installation so I'm guessing you're not. 
In the next autoexporter update you wont need to download the pak files, so this should eliminate that issue.

**Comment by ClashSupreme** [comment]
> Are you sure you're using the 14.30 Pak files? This is pretty much one of the only reasons why you would be getting this error. Your pak directory is set to the default fortnite installation so I'm guessing you're not.
> In the next autoexporter update you wont need to download the pak files, so this should eliminate that issue.

So do I have to wait for a new updated autoexporter? Or is it something with my pak files, because my fortnite is up to date

**Comment by halfuwu** [comment]
You've got to use an older version of Fortnite, version 14.30, as it's the last version that's supported by umodel. The new update won't require you to have these game files.

**Comment by ClashSupreme** [comment]
> You've got to use an older version of Fortnite, version 14.30, as it's the last version that's supported by umodel. The new update won't require you to have these game files.

Is there a way to get the older version of those files? Since I have the new paks. How can I get them?

**Comment by halfuwu** [comment]
Updated to work on the latest version
