### ISSUE TITLE
heads not being textured

### ISSUE THREAD

**Issue by D3fa1t1** [halfuwu/FortniteAutoExporter#8]
The heads arent textured
![image](https://user-images.githubusercontent.com/77608590/104900167-09ca4600-597c-11eb-8dca-6f39ecb91324.png)
one example
![image](https://user-images.githubusercontent.com/77608590/104900252-25cde780-597c-11eb-914a-fca57b35b54c.png)
and another. this happens with every head.

further testing is done

**Comment by D3fa1t1** [comment]
exept for Satah_02 apperently

**Comment by halfuwu** [comment]
Made some adjustments and it seems to work fine for me, should be fixed in the next update.

**Comment by halfuwu** [comment]
![image](https://user-images.githubusercontent.com/69497698/104948065-aeec1b00-598a-11eb-9ace-05065b49de2a.png)
![image](https://user-images.githubusercontent.com/69497698/104948139-d2af6100-598a-11eb-8ec8-c0f071a12dc5.png)
![image](https://user-images.githubusercontent.com/69497698/104948207-ee1a6c00-598a-11eb-98f3-6f256789e6b8.png)
![image](https://user-images.githubusercontent.com/69497698/104948308-15713900-598b-11eb-8087-c077439c6169.png)

**Comment by D3fa1t1** [comment]
seems good now. also you could use "labels" btw instead of just closing the issues
